# Generated by Django 3.2.7 on 2021-09-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostpaidDongleCustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('planid', models.IntegerField()),
                ('activatestatus', models.BooleanField()),
                ('pactivateddate', models.DateTimeField()),
                ('pexpirydate', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PrepaidMobilePlansModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pvalidity', models.IntegerField()),
                ('pdata', models.IntegerField()),
                ('ptalktime', models.IntegerField()),
                ('psms', models.IntegerField()),
                ('ptype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('device', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('aadhar', models.BigIntegerField()),
            ],
        ),
    ]
