# Generated by Django 3.2.7 on 2021-09-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceapp', '0002_postpaiddonglecustomermodel_prepaidmobileplansmodel_registermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaidMobileCustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('planid', models.IntegerField()),
                ('activatestatus', models.BooleanField()),
                ('pactivateddate', models.DateTimeField()),
                ('pexpirydate', models.DateTimeField(default=None)),
            ],
        ),
    ]
