# Generated by Django 3.2.7 on 2021-09-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceapp', '0003_prepaidmobilecustomermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPrepaidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billnumber', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('planid', models.IntegerField()),
                ('transactiontype', models.CharField(max_length=50)),
                ('pactivateddate', models.DateTimeField()),
            ],
        ),
    ]
