# Generated by Django 3.2.7 on 2021-09-08 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceapp', '0004_billprepaidmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountsummarypost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_bal', models.IntegerField()),
                ('Adjustment', models.CharField(max_length=50)),
                ('month_charge', models.CharField(max_length=50)),
                ('amount_due', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filldetailpostpaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('address_1', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Monthchargepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rent', models.IntegerField()),
                ('usage', models.CharField(max_length=50)),
                ('one_time_charge', models.IntegerField()),
                ('discounts', models.IntegerField()),
                ('taxes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanPostpaidMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.IntegerField()),
                ('data', models.IntegerField()),
                ('SMS', models.IntegerField()),
                ('calls', models.CharField(max_length=50)),
                ('subs', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicepostpaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField()),
                ('bill_data', models.CharField(max_length=50)),
                ('bill_period', models.CharField(max_length=50)),
                ('pay_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usagepostpaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.IntegerField()),
                ('plan_status', models.CharField(max_length=50)),
                ('used_data', models.IntegerField()),
                ('used_sms', models.IntegerField()),
                ('used_call', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='billprepaidmodel',
            name='pactivateddate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
