# Generated by Django 3.2.6 on 2021-09-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceapp', '0006_registermodel_aadharfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='aadharfile',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
