# Generated by Django 3.2.7 on 2021-09-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceapp', '0007_alter_registermodel_aadharfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='aadharfile',
        ),
        migrations.AddField(
            model_name='registermodel',
            name='aadharphoto',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
