# Generated by Django 3.2.7 on 2021-09-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceapp', '0009_registermodel_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidmobilecustomermodel',
            name='paymentype',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
