# Generated by Django 3.2.6 on 2021-09-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceapp', '0010_prepaidmobilecustomermodel_paymentype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddloginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='contactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usagemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planid', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('cdata', models.IntegerField(default=None)),
                ('csms', models.IntegerField(default=None)),
                ('cvalidity', models.IntegerField(default=None)),
                ('cvoice', models.IntegerField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='prepaiddonglecustomermodel',
            name='paymentype',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='prepaidmobilecustomermodel',
            name='pcurrentdate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='prepaidmobilecustomermodel',
            name='pdata',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='prepaidmobilecustomermodel',
            name='psms',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='prepaidmobilecustomermodel',
            name='pvalidity',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='prepaidmobilecustomermodel',
            name='pvoice',
            field=models.IntegerField(default=None),
        ),
    ]
