# Generated by Django 3.2.7 on 2021-09-16 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceapp', '0011_auto_20210915_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminloginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eusername', models.CharField(max_length=200)),
                ('epassword', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AdminRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=200)),
                ('eemail', models.CharField(max_length=200)),
                ('epassword', models.CharField(max_length=200)),
                ('emobile', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billnumber', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('planid', models.IntegerField()),
                ('transactiontype', models.CharField(max_length=50)),
                ('pactivateddate', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.IntegerField()),
                ('billfile', models.FileField(default=None, upload_to='bill/')),
                ('servicetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dongleregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=50)),
                ('daddress', models.CharField(max_length=50)),
                ('daddress_1', models.CharField(max_length=50)),
                ('dcity', models.CharField(max_length=50)),
                ('dstate', models.CharField(max_length=50)),
                ('dpincode', models.CharField(max_length=50)),
                ('demail', models.CharField(max_length=50)),
                ('dphn', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='BillPrepaidModel',
        ),
        migrations.AddField(
            model_name='prepaidmobilecustomermodel',
            name='planname',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
