# Generated by Django 3.2.7 on 2021-09-16 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceapp', '0013_remove_billmodel_billfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillManagementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billnumber', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('planid', models.IntegerField()),
                ('transactiontype', models.CharField(max_length=50)),
                ('pactivateddate', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.IntegerField()),
                ('servicetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='BillModel',
        ),
    ]
