# Generated by Django 3.2.6 on 2021-08-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pcode', models.IntegerField()),
                ('Pname', models.CharField(max_length=25)),
                ('Pdescription', models.CharField(max_length=25)),
                ('Pprice', models.IntegerField()),
            ],
        ),
    ]
